apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: demo-pipeline
spec:
  resources:
    - name: git-repo
      type: git
    - name: image-resource
      type: image
  tasks:
    - name: test
      taskRef:
        name: task-test
      resources:
        inputs:
          - name: git-repo
            resource: git-repo
    - name: build-and-publish
      taskRef: 
        name: kaniko
      resources:
        inputs:
          - name: source
            resource: git-repo
        outputs:
          - name: image
            resource: image-resource
