apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: resource-git
  namespace: default
spec:
  type: git
  params:
    - name: url
      value: https://github.com/CarlosMRDuarte/cicd-demo
    - name: revision
      value: master
