# ---
# kind: pipeline
# type: docker
# name: default

# steps:
# - name: test
#   image: plugins/docker
#   settings:
#     username: # Your docker hub account username
#     password: # Your docker hub password
#     repo: # Create one repository to store the image
#     tags: latest

kind: pipeline
name: default

steps:
  - name: test
    image: maven:3-jdk-11
    commands:
      - mvn test
